import { StyleSheet, Text, View, ScrollView, Dimensions, Image, TouchableOpacity} from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaView } from 'react-native';
import Navigation from '../src/components/Footer';
import { useNavigation } from "@react-navigation/native";
import NewsPaperProps from '../src/components/newsPaperProps';
import NewsPaperProps1 from '../src/components/newsPaperProps1';
import Footer from '../src/components/Footer';

export default function NewsPaper(){
    const navigation = useNavigation()
    return(
        <View className ="flex-1 relative bg-white">
            <StatusBar style='dark'/>

            <SafeAreaView className ="flex-1">

            <View className="w-full absolute top-12">
             <View className ="px-12 flex-row justify-between items-center">
                
             <TouchableOpacity onPress={() => navigation.replace('Foryou')}>
                    <Text className ="text-base font-semibold" >
                        For you
                    </Text >
                </TouchableOpacity>
                    <TouchableOpacity onPress={() => navigation.replace('Says')}>
                    <Text  className ="text-base font-semibold" >
                        Say
                    </Text>  
                    </TouchableOpacity>
                    <TouchableOpacity onPress={() => navigation.replace('Shops')}>
                    <Text  className ="text-base font-semibold">
                        Shops
                    </Text>
                    </TouchableOpacity>
                
            </View>
            </View>
            <View className ="mt-10 py-2">
            <ScrollView
             pagingEnabled
             horizontal
             showsHorizontalScrollIndicator={false}
             showsVerticalScrollIndicator ={false}
             
            >
            <NewsPaperProps/>
            <NewsPaperProps1 Description ="As soon as I sat down with the cofounders to talk about this new launch I immediately had to ask what took them so long to create a sunscreen. We had to make sure it was perfect, they both say, almost in tandem. It took us over 50 tries to get it right, says Laxton. The first version was actually back in 2020 and was a complete failure. We'll never launch something just to launch it. We needed it to be up to Inkey standards, she adds."


            Description1 ="

            What defines a perfect sunscreen? To Curry, cofounder of Inkey List and the R&D lead, it must offer really strong sun protection and a bonus active ingredient (in this case, it's polyglutamic acid or PGA.) It also needs to layer well with other products, including makeup and, most importantly for many of us, have a blendable, white-cast-free finish to ensure it works for all skin tones."
            Description2 = "A glance at the product name and you're probably wondering what PGA is. Curry wanted to include an ingredient that would hydrate the skin without causing piling when it's layered with other skin-care products or makeup."
            smallTitle ="Let’s Talk About The Ingredients List"
            />

            <NewsPaperProps1
            Description ="According to cosmetic chemist Kelly Dobos, PGA is a hydration powerhouse. It is a naturally occurring component of the sticky paste found in the Japanese fermented soybean dish called natto, says Dobos. She adds that while you might hear polyglutamic acid can hold up to 5,000 times its weight in water, this type of data is generated by evaluating the ingredient by itself. When it’s in a formula with other ingredients, like in this sunscreen, it's far less but still very effective at increasing skin moisture. In addition to PGA, the formula also contains squalane and glycerin, which add to the hydration packed into the tiny tube."
            Description1 ="Connecticut-based, board-certified dermatologist Mona Gohara, MD, agrees with Dobos's assessment and states that PGA can absorb four times the amount of water as hyaluronic acid and is proven to plump and bring radiance to the skin, which would explain the dewy finish the sunscreen leaves behind.
            "
            Description2 ="But that's not the only standout component in the tube. Dobos points out a few other stars on the ingredients list. These definitely aren't the sexiest ingredient names, but they are pretty great: C9-12 alkane and coco-caprylate, she says. These both have naturally derived emollients that are being used as a substitute for cyclic silicones.These two make the sunscreen look glowy without feeling oily or greasy.
            And, most importantly, the protection factor: Polyglutamic Acid Dewy Sunscreen is formulated to provide a broad-spectrum SPF 30 shield, thanks to common sunscreen ingredients, including avobenozone, ensulizole, octisalate, and octocrylene. Also noting that while this is a chemical sunscreen, it contains no oxybenzone or octinoxate, which are believed to be harmful to coral reefs.
            "
            />
            </ScrollView>
            </View>
            
           

            </SafeAreaView>

            <Footer/>
            </View>
    );
}